name: Tests fonctionnels du tp3
on:
  push:
    branches:
      - tp3
jobs:
  job1:
    name: Verification
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: affichage
      run: |
        echo $OSTYPE
        gcc -v
        ls -la
  job2:
    name: Tests fonctionnels
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: evenement 00
      run: |
        make clean
        make tp3
        cat tests/event00_in.txt | ./tp3 | diff -b tests/event00_out.txt -
    - name : evenement 01
      run: |
        cat tests/event01_in.txt | ./tp3 -d | diff -b tests/event01_out.txt -
    - name : evenement 02
      run: |
        cat tests/event02_in.txt | ./tp3 -d | diff -b tests/event02_out.txt -
    - name : evenement 03
      run: |
        cat tests/event03_in.txt | ./tp3 -d | diff -b tests/event03_out.txt -
    - name : evenement 04
      run: |
        cat tests/event04_in.txt | ./tp3 -d | diff -b tests/event04_out.txt -
