name: tp2 compilation
on:
  push:
    branches:
      - tp2
    paths:
      - 'tp2.c'
      - 'malib.c'
      - 'tcv.o'
      - '.github/workflows/tp2.yml'
jobs:
  job1:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: affichage
      run: |
        echo $OSTYPE
        gcc -v
    - name: compilation
      run: |
        curl https://github.com/guyfrancoeur/INF3135_A2020/raw/master/tp/tp1.zip
        unzip tp1.zip
        gcc -std=c11 -Wall -Werror=vla -pedantic -o tp2 tp2.c malib.c tcv.o -lm
