name: Tp2 compilation
on:
  push:
    branches:
      - tp2
jobs:
  job1:
    name: Verification
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: affichage
      run: |
        echo $OSTYPE
        gcc -v
        ls -la
    - name: Lib/Install
      run: |
        wget https://github.com/guyfrancoeur/INF3135_A2020/raw/master/tp/tp1.zip
        unzip tp1.zip
        sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev
    - name: Compilation tp1
      run:  
        gcc -std=c11 -Wall -Werror=vla -pedantic -I/usr/include/CUnit -L/usr/lib/x86_64-linux-gnu -o tp1 tp1.c simple.c tcv.o -lcunit 
    - name: Compilation tp2
      run: 
        gcc -std=c11 -Wall -Werror=vla -pedantic -o tp2 tp2.c malib.c tcv.o -lm
    - name: File
      run: |
        file tp1
        file tp2
